
try{
    var a = factorial(-1); // -> will cause an exception
}catch(err) {

    console.log(err); // prints "factorial undefined for -1" to the console

}
